server:
  port: 8081
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/hfaravenak/Mingetal-Client-Management
          search-paths: "config-data-docker"
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  # INICIO DE LOS CAMBIOS CRUCIALES AQUÍ
  metrics:
    system:
      enabled: false # <--- MODIFICACIÓN: Deshabilita las métricas del sistema
    enable:
      all: false     # <--- MODIFICACIÓN: Deshabilita todas las métricas si la anterior no es suficiente
  # FIN DE LOS CAMBIOS CRUCIALES