version: "3.8"
services:
  config:
    container_name: config_mingetal
    image: simonsaez/config_mingetal
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka:
    container_name: eureka_mingetal
    image: simonsaez/eureka_mingetal
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      config:
        condition: service_healthy

  postgres-proveedor-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: proveedor
      POSTGRES_PASSWORD: Simon_789
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  proveedor:
    container_name: proveedor_mingetal
    image: simonsaez/proveedor_mingetal
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-proveedor-db:5432/proveedor
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Simon_789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      postgres-proveedor-db:
        condition: service_started
      eureka:
        condition: service_healthy

  postgres-login-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: login
      POSTGRES_PASSWORD: Simon_789
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
  login:
    container_name: Login_mingetal
    image: simonsaez/login_mingetal
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-login-db:5432/login
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Simon_789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      postgres-login-db:
        condition: service_started
      eureka:
        condition: service_healthy

  postgres-productos-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: productos
      POSTGRES_PASSWORD: Simon_789
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"
  productos:
    container_name: productos_mingetal
    image: simonsaez/productos_mingetal
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-productos-db:5432/productos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Simon_789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      postgres-productos-db:
        condition: service_started
      eureka:
        condition: service_healthy

  postgres-cliente-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: cliente
      POSTGRES_PASSWORD: Simon_789
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"
  cliente:
    container_name: cliente_mingetal
    image: simonsaez/cliente_mingetal
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-cliente-db:5432/cliente
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Simon_789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      postgres-cliente-db:
        condition: service_started
      eureka:
        condition: service_healthy

  postgres-ordenesDeCompra-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: ordenesDeCompra
      POSTGRES_PASSWORD: Simon_789
      POSTGRES_USER: postgres
    ports:
      - "5437:5432"
  ordenes-de-compra:
    container_name: ordenes-de-compra_mingetal
    image: simonsaez/ordenes-de-compra_mingetal
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ordenesDeCompra-db:5432/ordenesDeCompra
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Simon_789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      postgres-ordenesDeCompra-db:
        condition: service_started
      eureka:
        condition: service_healthy

  gateway:
    container_name: gateway_mingetal
    image: simonsaez/gateway_mingetal
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI= http://config:8081
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  frontend-mcm:
    container_name: frontend-mcm_mingetal
    image: simonsaez/frontend-mcm_mingetal
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - login
      - gateway
      - ordenes-de-compra
      - cliente
      - productos
      - proveedor