insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'BY FLOWER BB', 38760, 82487, 17);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Nu Skin Clear Action', 30021, 59031, 20);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Fluvoxamine Maleate', 46881, 84724, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Food - Fish and Shellfish, Shrimp Crago sp.', 35778, 90758, 10);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Anpituapar', 24577, 97369, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Quetiapine fumarate', 21723, 58838, 4);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Triamterene hydrochlorothiazide', 31462, 63911, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'Childrens Ibuprofen', 32177, 87625, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'quetiapine fumarate', 28761, 95859, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Propranolol Hydrochloride', 38591, 82369, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Treatment Set TS330533', 37551, 61367, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Cyclobenzaprine Hydrochloride', 36480, 69447, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Telmisartan', 31661, 83027, 15);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'Oxygen', 43823, 85946, 3);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Homeopathic Bronchitis Formula', 41503, 86857, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Fexofenadine Hydrochloride', 20642, 70868, 5);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Emtriva', 33693, 59062, 15);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Alternaria alternata', 34485, 53083, 2);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Colgate Anticavity', 21316, 95116, 3);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Preferred Plus TabTussin', 29238, 93829, 10);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Aplicare Povidone-iodine Perineal Wash', 30535, 75503, 19);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Mountain Cedar', 27923, 50472, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Dollar General Gold', 48372, 92234, 19);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Deferoxamine Mesylate', 48917, 59969, 5);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Metronidazole', 40198, 95862, 1);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Clearasil Daily Clear', 36694, 77005, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Ranitidine Hydrochloride', 28937, 95393, 15);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'Motion Sickness II', 27846, 53990, 11);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Suprane', 42031, 52588, 18);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'Dr. Dream Cold Plazma Whitening', 37732, 76436, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Molds, Rusts and Smuts, Epicoccum nigrum', 36541, 54855, 2);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'LBEL', 41322, 59371, 14);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'Dendracin Neurodendraxcin', 30529, 96589, 1);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'THE ORIGINAL NATURAL HERB COUGH DROPS', 45838, 55615, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Lisinopril', 46952, 66375, 6);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'Neutrogena Men', 28948, 94428, 11);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'SKELAXIN', 28911, 91276, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Natural Fiber', 42720, 90592, 4);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Atorvastatin Calcium', 47600, 85692, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'Haloperidol Decanoate', 26795, 92611, 4);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Voltaren', 42925, 51513, 12);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Lisinopril', 43480, 52834, 11);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Giltuss', 24672, 99714, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Aspirin Chewable', 20908, 92093, 19);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Kids Crest', 22949, 76695, 9);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Cyclobenzaprine Hydrochloride', 36544, 77647, 18);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'smart sense tussin cf', 37502, 88262, 17);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Helium', 47385, 83614, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'NUX VOMICA', 37455, 80355, 20);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Levocetirizine Dihydrochloride', 21929, 59656, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Loperamide Hydrochloride', 25955, 52059, 5);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'rexall ibuprofen', 20799, 80971, 20);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Gemcitabine Hydrochloride', 46317, 89504, 11);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Esmolol Hydrochloride', 36618, 90300, 15);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Captopril', 37390, 99296, 8);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Gemcitabine', 38447, 95916, 19);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'FLURA-DROPS', 26360, 53281, 11);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Kroger', 42986, 93537, 0);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Rocky Mountain KIDS Broad Spectrum SPF 30', 42763, 61903, 4);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Losartan Potassium and Hydrochlorothiazide', 21078, 56909, 2);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'risperidone', 37349, 85163, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Naproxen Tablets', 25924, 63850, 4);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'Citalopram', 40192, 57630, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Icy Hot Medicated Roll Large', 43017, 68246, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'healthy accents cold and cough DM', 28032, 79026, 2);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Hydralazine Hydrochloride', 42232, 94989, 20);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Rescue', 21680, 99265, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Dilaudid', 44576, 73948, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Plum Duo Emergency Eyewash pH Neutralizing', 39398, 98900, 16);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'Loma Lux Psoriasis', 39225, 72106, 12);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Lorazepam', 33328, 77245, 12);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Oxygen', 23706, 79185, 4);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Sleep Aid', 43082, 84803, 2);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Brass', 'Intervene Makeup SPF 15 Soft Toffee', 30741, 72609, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'NWC 21 NATURAL PREMIUM BB CREAM', 28030, 70966, 5);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Desert Bambu', 41439, 96934, 9);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Match Perfection SPF 18', 49144, 62563, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'DOUBLE PERFECTION LUMIERE', 24758, 90021, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Belli Pure Radiance Facial Sunscreen Tinted Protection SPF 25', 40001, 51636, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Ketoconazole', 24684, 83688, 0);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Lamotrigine', 24794, 65107, 14);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plastic', 'Deb Med Antimicrobial Foaming Hand Wash', 21527, 57368, 9);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Baclofen', 27857, 71048, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Dexamethasone', 47906, 76181, 12);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'Good Sense Childrens Cold and Cough', 42476, 62280, 20);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Paroxetine', 34839, 57292, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Aquavit 1', 28835, 88460, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'TriNessa', 26527, 92787, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'quetiapine fumarate', 26675, 90892, 9);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'Potassium Chloride', 44522, 57314, 14);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Wood', 'ZONISAMIDE', 38649, 92796, 6);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Glass', 'Flexible', 36597, 93318, 13);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Aluminum', 'Sovaldi', 38207, 57368, 12);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Dorzolamide Hydrochloride and Timolol Maleate', 42800, 80518, 14);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Plexiglass', 'Mirtazapine', 36173, 86056, 0);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Thario Instant Hand Sanitizer', 30869, 74380, 7);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Granite', 'TOFRANIL', 48698, 94377, 18);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Vinyl', 'Mucor', 33075, 87596, 5);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Amoxicillin', 31361, 84552, 9);
insert into Productos (tipo, nombre, valor, valor_final, cantidad) values ('Stone', 'Testosterone', 25406, 86075, 11);